spring:
  application:
    name: farm-management
    title: DraFarm
    version: 1.0
    # config Entity to Snake_case in database
  jackson:
    property-naming-strategy: SNAKE_CASE
    # connect database postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cqu0i3bv2p9s73cuoiig-a.singapore-postgres.render.com/farm_management_hsyi
    username: farm_management_hsyi_user
    password: dUMLaC6eu9zdMj25dAVovf3XdLgvNkBo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
